### ISSUE TITLE
Trouble in cloning the repository due to invalid path

### ISSUE THREAD

**Issue by ayushtamra** [codechefvitbhopal/Resource-Buffer#116]
Hello!!
I just observed due to a invalid file name or path, I am not able to clone the repository into my local
The error was this:
`error: invalid path 'Week 1: Coding Fundamentals/ProblemSet/General Solutions/Aalok_20BCG10044_q1'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
`
Please tell if there is any solution for it.

**Comment by Vishesht27** [comment]
Hey, 
I guess the path is correct , because everyone else is able to submit their solution easily.

https://www.youtube.com/watch?v=YMtMMZjaFWM
